// Adeka Academy Hub — Quiz Question Bank
//
// This file is intentionally separate from index.html so it's easy to
// keep growing the question bank without touching any app code. Just
// add more objects to the right subject's array, following the same
// { q, options, answer } shape (answer is the index, 0-3, of the
// correct option).
//
// Current size: 25 questions per subject (300 total). Target is ~100
// per subject — more batches will be added over time.

const QUIZ_DATA = {
JHS: {
label: "Junior High School (JHS)",
subjects: {
"Mathematics": [
{ q: "What is 15 + 27?", options: ["32","42","41","52"], answer: 1 },
{ q: "Simplify: 3x + 5x", options: ["8x","15x","8x\u00b2","53x"], answer: 0 },
{ q: "What is 7 \u00d7 8?", options: ["54","56","64","49"], answer: 1 },
{ q: "Which of these is a prime number?", options: ["9","15","17","21"], answer: 2 },
{ q: "What is half of 90?", options: ["40","45","50","55"], answer: 1 },
{ q: "What is 12 \u00d7 12?", options: ["120","144","132","154"], answer: 1 },
{ q: "Which of these numbers is even?", options: ["15","22","33","41"], answer: 1 },
{ q: "What is 100 \u00f7 4?", options: ["20","25","30","40"], answer: 1 },
{ q: "What is the perimeter of a square with side 5cm?", options: ["15cm","20cm","25cm","10cm"], answer: 1 },
{ q: "Which of these decimals is the smallest?", options: ["0.5","0.05","0.55","They are equal"], answer: 1 },
{ q: "What is 84 - 37?", options: ["37","47","57","67"], answer: 1 },
{ q: "What is 1/2 + 1/4?", options: ["1/2","2/4","3/4","1"], answer: 2 },
{ q: "What is the area of a rectangle 6cm by 4cm?", options: ["10cm\u00b2","20cm\u00b2","24cm\u00b2","28cm\u00b2"], answer: 2 },
{ q: "What is 9 \u00d7 9?", options: ["72","81","91","99"], answer: 1 },
{ q: "Round 67 to the nearest 10.", options: ["60","65","70","75"], answer: 2 },
{ q: "Simplify the ratio 8:4.", options: ["4:1","2:1","1:2","8:1"], answer: 1 },
{ q: "What is 50% of 80?", options: ["20","30","40","50"], answer: 2 },
{ q: "What type of angle measures exactly 90 degrees?", options: ["Acute","Obtuse","Right","Reflex"], answer: 2 },
{ q: "What is 5 + 3 \u00d7 2?", options: ["16","11","13","10"], answer: 1 },
{ q: "What is -5 + 8?", options: ["-13","-3","3","13"], answer: 2 },
{ q: "What is the square root of 49?", options: ["6","7","8","9"], answer: 1 },
{ q: "Find the average of 4, 6, and 8.", options: ["5","6","7","8"], answer: 1 },
{ q: "How many minutes are in 2 hours?", options: ["100","110","120","130"], answer: 2 },
{ q: "What is 6 \u00d7 7?", options: ["36","40","42","48"], answer: 2 },
{ q: "What is the next number in the pattern 2, 4, 6, 8, ___?", options: ["9","10","12","14"], answer: 1 }
],
"English Language": [
{ q: "Choose the correct spelling.", options: ["Recieve","Receive","Receeve","Receve"], answer: 1 },
{ q: "What is the plural of \"child\"?", options: ["Childs","Childes","Children","Childrens"], answer: 2 },
{ q: "Identify the noun in: \"The dog barked loudly.\"", options: ["barked","loudly","dog","the"], answer: 2 },
{ q: "Choose the synonym for \"happy\".", options: ["Sad","Joyful","Angry","Tired"], answer: 1 },
{ q: "Which sentence is correct?", options: ["She is went to school.","She go to school.","She goes to school.","She going to school."], answer: 2 },
{ q: "Choose the correct article: \"___ apple a day keeps the doctor away.\"", options: ["A","An","The","No article"], answer: 1 },
{ q: "What is the past tense of \"go\"?", options: ["Goed","Gone","Went","Going"], answer: 2 },
{ q: "Identify the verb in: \"She sings beautifully.\"", options: ["She","sings","beautifully","(none)"], answer: 1 },
{ q: "Choose the correct word: \"There ___ many students in the hall.\"", options: ["is","was","were","be"], answer: 2 },
{ q: "What is the opposite of \"difficult\"?", options: ["Hard","Easy","Tough","Complex"], answer: 1 },
{ q: "Choose the correct plural of \"mouse\".", options: ["Mouses","Mices","Mice","Mouse"], answer: 2 },
{ q: "Identify the adjective: \"The tall boy ran fast.\"", options: ["boy","ran","tall","fast"], answer: 2 },
{ q: "What is the past tense of \"eat\"?", options: ["Eated","Ate","Eaten","Eating"], answer: 1 },
{ q: "Choose the correct preposition: \"The book is ___ the table.\"", options: ["on","in","at","by"], answer: 0 },
{ q: "What is a \"pronoun\"?", options: ["A word that describes a noun","A word that replaces a noun","A type of verb","A type of adjective"], answer: 1 },
{ q: "Choose the correctly spelled word.", options: ["Beleive","Believe","Belive","Beleve"], answer: 1 },
{ q: "What is the plural of \"box\"?", options: ["Boxs","Boxes","Boxies","Box"], answer: 1 },
{ q: "Identify the conjunction in: \"I like tea and coffee.\"", options: ["like","tea","and","coffee"], answer: 2 },
{ q: "What is the opposite of \"big\"?", options: ["Large","Huge","Small","Tall"], answer: 2 },
{ q: "Choose the correct sentence.", options: ["He don't like rice.","He doesn't like rice.","He not like rice.","He no like rice."], answer: 1 },
{ q: "What punctuation mark ends a question?", options: ["Period","Comma","Question mark","Exclamation mark"], answer: 2 },
{ q: "Identify the adverb in: \"She sang loudly.\"", options: ["She","sang","loudly","(none)"], answer: 2 },
{ q: "What is a synonym for \"fast\"?", options: ["Slow","Quick","Lazy","Tired"], answer: 1 },
{ q: "Choose the correct possessive form: \"This is ___ book.\"", options: ["my","I","me","mine is"], answer: 0 },
{ q: "What is the term for words that have the same meaning?", options: ["Antonyms","Synonyms","Homophones","Pronouns"], answer: 1 }
],
"Integrated Science": [
{ q: "What gas do plants absorb from the air for photosynthesis?", options: ["Oxygen","Nitrogen","Carbon dioxide","Hydrogen"], answer: 2 },
{ q: "The human body has how many lungs?", options: ["1","2","3","4"], answer: 1 },
{ q: "Water boils at what temperature (\u00b0C) at sea level?", options: ["50","90","100","120"], answer: 2 },
{ q: "Which organ pumps blood around the body?", options: ["Liver","Heart","Kidney","Lungs"], answer: 1 },
{ q: "What is the process by which plants make food called?", options: ["Respiration","Digestion","Photosynthesis","Evaporation"], answer: 2 },
{ q: "Which of these is a renewable source of energy?", options: ["Coal","Solar","Natural gas","Petroleum"], answer: 1 },
{ q: "What do we call animals that eat only plants?", options: ["Carnivores","Herbivores","Omnivores","Predators"], answer: 1 },
{ q: "Which part of a plant absorbs water from the soil?", options: ["Leaf","Stem","Root","Flower"], answer: 2 },
{ q: "What is the freezing point of water in Celsius?", options: ["0","10","32","100"], answer: 0 },
{ q: "Which gas do humans breathe in for survival?", options: ["Carbon dioxide","Oxygen","Nitrogen","Hydrogen"], answer: 1 },
{ q: "What is the largest organ in the human body?", options: ["Heart","Liver","Skin","Brain"], answer: 2 },
{ q: "Which planet is closest to the Sun?", options: ["Earth","Venus","Mercury","Mars"], answer: 2 },
{ q: "What do we call animals that eat both plants and meat?", options: ["Herbivores","Carnivores","Omnivores","Decomposers"], answer: 2 },
{ q: "What is the chemical symbol for oxygen?", options: ["O","Ox","O2","Og"], answer: 0 },
{ q: "Which part of the eye controls the amount of light entering?", options: ["Retina","Pupil","Cornea","Lens"], answer: 1 },
{ q: "What state of matter has no fixed shape or volume?", options: ["Solid","Liquid","Gas","Plasma"], answer: 2 },
{ q: "What is the main function of the kidneys?", options: ["Pumping blood","Filtering waste from blood","Digesting food","Producing hormones only"], answer: 1 },
{ q: "Which of these is NOT a source of light?", options: ["Sun","Bulb","Mirror","Candle"], answer: 2 },
{ q: "What do plants need to undergo photosynthesis besides water and carbon dioxide?", options: ["Soil","Sunlight","Oxygen","Nitrogen"], answer: 1 },
{ q: "What is the smallest unit of living matter?", options: ["Tissue","Organ","Cell","Organism"], answer: 2 },
{ q: "Which gas do plants release during photosynthesis?", options: ["Carbon dioxide","Oxygen","Nitrogen","Hydrogen"], answer: 1 },
{ q: "What is the boiling point of water in Fahrenheit?", options: ["100\u00b0F","180\u00b0F","212\u00b0F","32\u00b0F"], answer: 2 },
{ q: "Which organ is responsible for pumping blood?", options: ["Lungs","Heart","Liver","Stomach"], answer: 1 },
{ q: "What do we call the force that opposes motion between surfaces?", options: ["Gravity","Friction","Tension","Magnetism"], answer: 1 },
{ q: "Which of these is a non-renewable energy source?", options: ["Solar","Wind","Coal","Hydro"], answer: 2 }
],
"Social Studies": [
{ q: "What is the capital city of Ghana?", options: ["Kumasi","Accra","Takoradi","Ho"], answer: 1 },
{ q: "Which of these is a branch of government?", options: ["Executive","Market","Factory","School"], answer: 0 },
{ q: "What do we call a person who leads a country as Head of State?", options: ["Minister","President","Governor","Mayor"], answer: 1 },
{ q: "Which continent is Ghana located in?", options: ["Asia","Africa","Europe","South America"], answer: 1 },
{ q: "What is the main purpose of the United Nations?", options: ["Trade only","Promote peace and cooperation","Sell goods","Build roads"], answer: 1 },
{ q: "Which document contains the laws of a country?", options: ["Newspaper","Constitution","Dictionary","Novel"], answer: 1 },
{ q: "What do we call the buying and selling of goods between countries?", options: ["Tourism","Trade","Farming","Mining"], answer: 1 },
{ q: "Who is responsible for making laws in a democracy?", options: ["Judges","Police","Parliament","Teachers"], answer: 2 },
{ q: "What is a community?", options: ["A single person","A group of people living together","A type of food","A building"], answer: 1 },
{ q: "Which of these promotes good citizenship?", options: ["Littering","Obeying laws","Avoiding taxes","Ignoring rules"], answer: 1 },
{ q: "What is the term for the study of the Earth's physical features?", options: ["History","Geography","Civics","Economics"], answer: 1 },
{ q: "Who is the traditional ruler of a Ghanaian town usually called?", options: ["President","Chief","Governor","Mayor"], answer: 1 },
{ q: "What is a 'right' in citizenship terms?", options: ["A privilege earned through wealth","A legal or moral entitlement","A type of punishment","A government building"], answer: 1 },
{ q: "Which of these is an example of a natural resource?", options: ["Factory","Gold","Car","Road"], answer: 1 },
{ q: "What does 'population' refer to?", options: ["The size of a country","The total number of people in an area","The number of animals only","A type of map"], answer: 1 },
{ q: "What is the main role of the police in society?", options: ["Make laws","Maintain law and order","Collect taxes","Build schools"], answer: 1 },
{ q: "Which of these is a fundamental human need?", options: ["Television","Shelter","Jewelry","Vacation"], answer: 1 },
{ q: "What is a 'map legend' used for?", options: ["Showing distance only","Explaining symbols used on a map","Showing population","Showing weather"], answer: 1 },
{ q: "What do we call money paid to the government from earnings?", options: ["Loan","Tax","Donation","Salary"], answer: 1 },
{ q: "Which continent is the largest by land area?", options: ["Africa","Europe","Asia","Antarctica"], answer: 2 },
{ q: "What is the term for moving from one country to settle in another?", options: ["Tourism","Migration","Trade","Exploration"], answer: 1 },
{ q: "What is the function of the family in society?", options: ["Only to provide food","Basic unit of socialization and support","To run businesses","To collect taxes"], answer: 1 },
{ q: "What is 'culture'?", options: ["A type of food","The way of life of a group of people","A government policy","A natural resource"], answer: 1 },
{ q: "Which of these is a renewable natural resource?", options: ["Forest","Crude oil","Coal","Natural gas"], answer: 0 },
{ q: "What is the term for a group of people living in the same area under one government?", options: ["Tribe","Nation","Family","Clan"], answer: 1 }
]
}
},
SHS: {
label: "Senior High School (SHS)",
subjects: {
"Core Mathematics": [
{ q: "Solve for x: 2x + 4 = 14", options: ["4","5","6","7"], answer: 1 },
{ q: "What is the value of 5\u00b2?", options: ["10","15","20","25"], answer: 3 },
{ q: "Simplify: (3 + 4) \u00d7 2", options: ["11","14","10","12"], answer: 1 },
{ q: "What is the gradient of a horizontal line?", options: ["1","Undefined","0","-1"], answer: 2 },
{ q: "Convert 0.75 to a fraction.", options: ["3/4","7/5","1/4","3/5"], answer: 0 },
{ q: "What is the value of 2\u00b3?", options: ["6","8","9","12"], answer: 1 },
{ q: "Solve: 3(x - 2) = 9", options: ["x=3","x=5","x=4","x=7"], answer: 1 },
{ q: "What is the sum of angles in a triangle?", options: ["90\u00b0","180\u00b0","270\u00b0","360\u00b0"], answer: 1 },
{ q: "What is 20% of 150?", options: ["20","30","25","35"], answer: 1 },
{ q: "Which of these is an irrational number?", options: ["1/2","0.75","\u221a2","4"], answer: 2 },
{ q: "Solve: 4x = 20.", options: ["x=4","x=5","x=6","x=8"], answer: 1 },
{ q: "What is the value of (3+5)\u00b2?", options: ["16","56","64","49"], answer: 2 },
{ q: "Simplify: 3x + 2x.", options: ["5x","6x","5x\u00b2","x"], answer: 0 },
{ q: "What is the slope of the line y = 3x + 2?", options: ["2","3","5","1"], answer: 1 },
{ q: "What is 15% of 200?", options: ["15","20","30","35"], answer: 2 },
{ q: "Solve for x: x - 7 = 13.", options: ["18","19","20","21"], answer: 2 },
{ q: "What is the value of 4\u00b3?", options: ["12","16","64","48"], answer: 2 },
{ q: "Which of these is a quadratic equation?", options: ["y = 2x + 1","y = x\u00b2 + 2","y = 1/x","y = 3"], answer: 1 },
{ q: "What is the perimeter of a rectangle with length 8cm and width 3cm?", options: ["11cm","16cm","22cm","24cm"], answer: 2 },
{ q: "Simplify: (2x)(3x).", options: ["5x","5x\u00b2","6x","6x\u00b2"], answer: 3 },
{ q: "What is the median of 3, 7, 9, 12, 15?", options: ["7","9","12","10"], answer: 1 },
{ q: "What is the value of \u221a81?", options: ["7","8","9","10"], answer: 2 },
{ q: "Solve: 2(x + 3) = 10.", options: ["x=1","x=2","x=3","x=4"], answer: 1 },
{ q: "What is the LCM of 4 and 6?", options: ["8","10","12","24"], answer: 2 },
{ q: "What is 7/8 expressed as a decimal?", options: ["0.785","0.875","0.75","0.95"], answer: 1 }
],
"English Language": [
{ q: "Choose the correct form: \"He ___ to school every day.\"", options: ["go","goes","going","gone"], answer: 1 },
{ q: "What part of speech is the word \"quickly\"?", options: ["Noun","Verb","Adjective","Adverb"], answer: 3 },
{ q: "Identify the antonym of \"generous\".", options: ["Kind","Selfish","Caring","Giving"], answer: 1 },
{ q: "Which word is spelled correctly?", options: ["Definately","Definitely","Definitly","Definatly"], answer: 1 },
{ q: "Choose the correctly punctuated sentence.", options: ["Let's eat, she said.","Lets eat, she said.","Let's eat she said.","Lets, eat she said."], answer: 0 },
{ q: "Identify the correct plural form of \"analysis\".", options: ["Analysises","Analyses","Analysis's","Analysies"], answer: 1 },
{ q: "Choose the correct conjunction: \"I stayed home ___ it was raining.\"", options: ["and","but","because","or"], answer: 2 },
{ q: "What is a metaphor?", options: ["A comparison using 'like' or 'as'","A comparison without using 'like' or 'as'","A type of rhyme","A question"], answer: 1 },
{ q: "Which sentence uses correct subject-verb agreement?", options: ["The team is playing well.","The team are playing well.","The team be playing well.","The team playing well."], answer: 0 },
{ q: "What is the term for a word that sounds the same as another but has a different meaning?", options: ["Synonym","Antonym","Homophone","Acronym"], answer: 2 },
{ q: "Identify the simile: \"He is as brave as a lion.\"", options: ["He is brave","as brave as a lion","He is a lion","brave lion"], answer: 1 },
{ q: "What is the term for a word opposite in meaning to another?", options: ["Synonym","Antonym","Homophone","Acronym"], answer: 1 },
{ q: "Choose the correct sentence.", options: ["Neither of them are correct.","Neither of them is correct.","Neither of them be correct.","Neither of them correct."], answer: 1 },
{ q: "What is personification?", options: ["Giving human traits to non-human things","Comparing two things using 'like'","Repeating a sound","A type of question"], answer: 0 },
{ q: "Identify the correct indirect speech: 'I am tired,' she said.", options: ["She said that she is tired.","She said that she was tired.","She say she was tired.","She said I am tired."], answer: 1 },
{ q: "What does the prefix 'un-' generally mean?", options: ["Again","Not","Before","Over"], answer: 1 },
{ q: "Choose the correct word: \"Their/There/They're going to school.\"", options: ["Their","There","They're","Their's"], answer: 2 },
{ q: "What is an idiom?", options: ["A literal expression","An expression whose meaning isn't literal","A type of punctuation","A grammar rule"], answer: 1 },
{ q: "Identify the correct comparative form of \"good\".", options: ["Gooder","Best","Better","More good"], answer: 2 },
{ q: "What is the function of a conjunction?", options: ["To describe a noun","To join words or clauses","To replace a noun","To show action"], answer: 1 },
{ q: "Choose the correctly spelled word.", options: ["Accomodate","Acommodate","Accommodate","Accomadate"], answer: 2 },
{ q: "What is alliteration?", options: ["Repetition of initial consonant sounds","A type of rhyme","A long sentence","A type of question"], answer: 0 },
{ q: "Identify the correct passive voice: \"The cat chased the mouse.\"", options: ["The mouse chased the cat.","The mouse was chased by the cat.","The cat was chased.","The mouse chases the cat."], answer: 1 },
{ q: "What is the term for a brief, witty statement?", options: ["Proverb","Epigram","Metaphor","Stanza"], answer: 1 },
{ q: "Choose the word that means 'very happy'.", options: ["Furious","Ecstatic","Anxious","Bored"], answer: 1 }
],
"Science": [
{ q: "What is the chemical symbol for water?", options: ["H2O","O2","CO2","HO2"], answer: 0 },
{ q: "Which part of the cell controls its activities?", options: ["Cytoplasm","Nucleus","Membrane","Mitochondria"], answer: 1 },
{ q: "What force pulls objects toward the Earth?", options: ["Magnetism","Friction","Gravity","Tension"], answer: 2 },
{ q: "What is the powerhouse of the cell?", options: ["Nucleus","Ribosome","Mitochondria","Golgi body"], answer: 2 },
{ q: "Sound travels fastest through:", options: ["Air","Water","Vacuum","Solids"], answer: 3 },
{ q: "What is the unit of electrical resistance?", options: ["Volt","Ampere","Ohm","Watt"], answer: 2 },
{ q: "Which organ filters blood to produce urine?", options: ["Liver","Kidney","Heart","Stomach"], answer: 1 },
{ q: "What type of energy is stored in food?", options: ["Kinetic","Potential","Chemical","Nuclear"], answer: 2 },
{ q: "Which of these is an example of a chemical change?", options: ["Melting ice","Burning wood","Boiling water","Cutting paper"], answer: 1 },
{ q: "What is the pH of a neutral substance?", options: ["0","7","14","10"], answer: 1 },
{ q: "What is the unit of force?", options: ["Joule","Newton","Watt","Pascal"], answer: 1 },
{ q: "Which organelle is responsible for protein synthesis?", options: ["Nucleus","Ribosome","Mitochondria","Golgi body"], answer: 1 },
{ q: "What is the pH of pure water?", options: ["5","6","7","8"], answer: 2 },
{ q: "What is the chemical formula for table salt?", options: ["NaCl","KCl","CaCl2","NaOH"], answer: 0 },
{ q: "Which law states that energy cannot be created or destroyed?", options: ["Newton's First Law","Law of Conservation of Energy","Law of Gravity","Ohm's Law"], answer: 1 },
{ q: "What is the process by which a liquid changes to a gas?", options: ["Condensation","Evaporation","Sublimation","Freezing"], answer: 1 },
{ q: "What is the main gas responsible for the greenhouse effect?", options: ["Oxygen","Nitrogen","Carbon dioxide","Helium"], answer: 2 },
{ q: "Which blood vessel carries oxygenated blood from the heart?", options: ["Vein","Artery","Capillary","Aorta only"], answer: 1 },
{ q: "What is the unit of electric current?", options: ["Volt","Ohm","Ampere","Watt"], answer: 2 },
{ q: "Which part of the brain controls balance?", options: ["Cerebrum","Cerebellum","Medulla","Hypothalamus"], answer: 1 },
{ q: "What type of rock is formed from cooled magma?", options: ["Sedimentary","Igneous","Metamorphic","Organic"], answer: 1 },
{ q: "What is the function of white blood cells?", options: ["Carry oxygen","Fight infection","Clot blood","Digest food"], answer: 1 },
{ q: "What is Newton's Third Law about?", options: ["Inertia","Action and reaction forces","Gravity","Acceleration"], answer: 1 },
{ q: "Which of these is an example of a physical change?", options: ["Burning wood","Melting ice","Rusting iron","Baking a cake"], answer: 1 },
{ q: "What is the main function of chlorophyll?", options: ["Store water","Absorb light for photosynthesis","Produce oxygen only","Protect the plant"], answer: 1 }
],
"Social Studies": [
{ q: "What is democracy?", options: ["Rule by one person","Government by the people","Rule by the military","Rule by the wealthy"], answer: 1 },
{ q: "What is the role of the judiciary in government?", options: ["Make laws","Interpret and apply laws","Collect taxes","Build infrastructure"], answer: 1 },
{ q: "What term describes movement of people from rural to urban areas?", options: ["Emigration","Urbanization","Immigration","Globalization"], answer: 1 },
{ q: "Which organization is Ghana a founding member of in Africa?", options: ["European Union","African Union","NATO","ASEAN"], answer: 1 },
{ q: "What is the term for a country's income from taxes used for public services?", options: ["Profit","Revenue","Loan","Debt"], answer: 1 },
{ q: "What does GDP stand for?", options: ["Gross Domestic Product","General Development Plan","Government Defense Policy","Global Demographic Profile"], answer: 0 },
{ q: "Which of these is a human right?", options: ["Right to education","Right to steal","Right to harm others","Right to ignore laws"], answer: 0 },
{ q: "What is the term for a system where power is shared between national and regional governments?", options: ["Unitary system","Federal system","Monarchy","Dictatorship"], answer: 1 },
{ q: "Who is the current head of the Ghanaian government typically called?", options: ["Prime Minister","President","Chancellor","Governor-General"], answer: 1 },
{ q: "What is the main goal of sustainable development?", options: ["Maximize profit only","Meet present needs without harming future generations","Increase pollution","Reduce population"], answer: 1 },
{ q: "What is the term for a country governed by its own citizens through elected representatives?", options: ["Monarchy","Democracy","Dictatorship","Theocracy"], answer: 1 },
{ q: "What is the role of an opposition party in parliament?", options: ["To support the ruling party always","To check and challenge government policies","To collect taxes","To enforce laws"], answer: 1 },
{ q: "What is 'inflation'?", options: ["A decrease in prices","A general increase in prices over time","A type of tax","A trade agreement"], answer: 1 },
{ q: "Which organization deals with international trade rules?", options: ["UN","WTO","WHO","UNESCO"], answer: 1 },
{ q: "What is meant by 'separation of powers'?", options: ["One branch controls all government functions","Government power is divided among different branches","Only the president has power","Citizens have no power"], answer: 1 },
{ q: "What is a 'pressure group'?", options: ["A government ministry","A group that seeks to influence government policy","A type of court","A military unit"], answer: 1 },
{ q: "What is the term for the movement of people within a country?", options: ["International migration","Internal migration","Emigration","Tourism"], answer: 1 },
{ q: "What does 'GDP' measure?", options: ["Population size","Total value of goods and services produced","Literacy rate","Land area"], answer: 1 },
{ q: "What is the main function of the central bank?", options: ["Build roads","Regulate the country's money supply","Collect taxes","Run schools"], answer: 1 },
{ q: "What is 'globalization'?", options: ["Isolation of countries","Increasing interconnection of world economies and cultures","A type of government","A form of currency"], answer: 1 },
{ q: "Which of these best describes 'civil society'?", options: ["The military","Organizations independent of government, e.g. NGOs","The judiciary","The police force"], answer: 1 },
{ q: "What is 'sustainable development'?", options: ["Development that ignores the environment","Development that meets present needs without compromising the future","Rapid industrialization only","Development funded only by loans"], answer: 1 },
{ q: "What does 'bicameral legislature' mean?", options: ["A legislature with one chamber","A legislature with two chambers","No legislature","A military council"], answer: 1 },
{ q: "What is the term for goods bought from other countries?", options: ["Exports","Imports","Tariffs","Subsidies"], answer: 1 },
{ q: "What is 'unemployment rate'?", options: ["Total population","Percentage of working-age people without jobs but seeking work","Number of businesses","Average income"], answer: 1 }
]
}
},
University: {
label: "University",
subjects: {
"Mathematics": [
{ q: "What is the derivative of x\u00b2?", options: ["x","2x","x\u00b2","2"], answer: 1 },
{ q: "What is the integral of 2x dx?", options: ["x\u00b2 + C","2x\u00b2 + C","x + C","x\u00b2/2 + C"], answer: 0 },
{ q: "What is the value of \u03c0 (to 2 decimal places)?", options: ["3.14","3.41","3.12","3.16"], answer: 0 },
{ q: "A matrix with equal rows and columns is called:", options: ["Rectangular","Square","Diagonal","Identity"], answer: 1 },
{ q: "What is log\u2081\u2080(100)?", options: ["1","2","10","100"], answer: 1 },
{ q: "What is the derivative of sin(x)?", options: ["cos(x)","-cos(x)","-sin(x)","sin(x)"], answer: 0 },
{ q: "What is the value of 0! (zero factorial)?", options: ["0","1","Undefined","-1"], answer: 1 },
{ q: "Which describes a function with no inverse over its full domain?", options: ["A bijective function","A one-to-one function","A many-to-one function","A linear function"], answer: 2 },
{ q: "What is the sum of the first 5 natural numbers (1 to 5)?", options: ["10","15","20","25"], answer: 1 },
{ q: "In a right triangle, which theorem relates the sides?", options: ["Pythagorean theorem","Binomial theorem","Bayes' theorem","Fermat's theorem"], answer: 0 },
{ q: "What is the derivative of cos(x)?", options: ["sin(x)","-sin(x)","cos(x)","-cos(x)"], answer: 1 },
{ q: "What is the integral of 1/x dx?", options: ["x + C","ln|x| + C","1/x\u00b2 + C","x\u00b2 + C"], answer: 1 },
{ q: "What is the determinant of a 2x2 identity matrix?", options: ["0","1","2","-1"], answer: 1 },
{ q: "What is the limit of (sin x)/x as x approaches 0?", options: ["0","1","\u221e","Undefined"], answer: 1 },
{ q: "What is the formula for the area of a circle?", options: ["2\u03c0r","\u03c0r\u00b2","\u03c0d","2\u03c0r\u00b2"], answer: 1 },
{ q: "What is e (Euler's number) approximately?", options: ["2.71","3.14","1.61","1.41"], answer: 0 },
{ q: "What is the rank of a zero matrix?", options: ["1","Undefined","0","Equal to its size"], answer: 2 },
{ q: "Which of these is an example of a vector quantity?", options: ["Mass","Temperature","Velocity","Time"], answer: 2 },
{ q: "What is the second derivative used to determine?", options: ["Slope only","Concavity of a function","The y-intercept","The domain"], answer: 1 },
{ q: "What is the solution set of x\u00b2 = 9?", options: ["{3}","{-3}","{3, -3}","{9}"], answer: 2 },
{ q: "What is a prime number?", options: ["A number divisible by many numbers","A number greater than 1 with no divisors other than 1 and itself","Any odd number","Any even number"], answer: 1 },
{ q: "What is the standard form of a linear equation?", options: ["y = mx + b","ax\u00b2 + bx + c = 0","a/b = c/d","y = a^x"], answer: 0 },
{ q: "What does 'orthogonal' mean in linear algebra?", options: ["Parallel","Perpendicular","Equal in length","Identical"], answer: 1 },
{ q: "What is the value of 5! (factorial)?", options: ["20","60","120","100"], answer: 2 },
{ q: "What is the formula for compound interest?", options: ["A = P(1+r)^t","A = P + r","A = Prt","A = P/r"], answer: 0 }
],
"Computer Science": [
{ q: "What does CPU stand for?", options: ["Central Process Unit","Central Processing Unit","Computer Personal Unit","Central Processor Utility"], answer: 1 },
{ q: "Which data structure uses LIFO (Last In, First Out)?", options: ["Queue","Stack","Array","Tree"], answer: 1 },
{ q: "What does HTML stand for?", options: ["HyperText Markup Language","HighText Machine Language","HyperText Markdown Language","HyperTransfer Markup Language"], answer: 0 },
{ q: "What is the time complexity of binary search?", options: ["O(n)","O(n\u00b2)","O(log n)","O(1)"], answer: 2 },
{ q: "Which of these is NOT a programming language?", options: ["Python","HTML","Java","Photoshop"], answer: 3 },
{ q: "What does RAM stand for?", options: ["Random Access Memory","Read Access Memory","Run Active Memory","Random Active Module"], answer: 0 },
{ q: "Which of these is an object-oriented programming concept?", options: ["Inheritance","Compilation","Indexing","Looping"], answer: 0 },
{ q: "What does SQL stand for?", options: ["Structured Query Language","Simple Query Logic","Structured Question Language","System Query Language"], answer: 0 },
{ q: "Which sorting algorithm has the best average-case time complexity?", options: ["Bubble Sort","Quick Sort","Selection Sort","Insertion Sort"], answer: 1 },
{ q: "What does the acronym \"API\" stand for?", options: ["Application Programming Interface","Advanced Programming Instruction","Applied Process Integration","Automated Program Interaction"], answer: 0 },
{ q: "What does 'GUI' stand for?", options: ["General User Interface","Graphical User Interface","Global User Input","Generated User Interface"], answer: 1 },
{ q: "Which of these is a NoSQL database?", options: ["MySQL","PostgreSQL","MongoDB","Oracle"], answer: 2 },
{ q: "What is recursion in programming?", options: ["A loop that never ends","A function that calls itself","A type of variable","A database query"], answer: 1 },
{ q: "What does 'IDE' stand for?", options: ["Integrated Development Environment","Internal Data Exchange","Internet Data Entry","Integrated Data Engine"], answer: 0 },
{ q: "What is the purpose of a firewall?", options: ["Speed up internet","Monitor and control network traffic for security","Store files","Run applications"], answer: 1 },
{ q: "Which data structure uses FIFO (First In, First Out)?", options: ["Stack","Queue","Tree","Graph"], answer: 1 },
{ q: "What does 'HTTP' stand for?", options: ["HyperText Transfer Protocol","High Transfer Text Protocol","HyperText Transmission Process","Host Transfer Text Protocol"], answer: 0 },
{ q: "What is an algorithm?", options: ["A programming language","A step-by-step procedure to solve a problem","A type of hardware","A database"], answer: 1 },
{ q: "Which of these is a version control system?", options: ["Git","Excel","Photoshop","Word"], answer: 0 },
{ q: "What does 'OOP' stand for?", options: ["Object-Oriented Programming","Open Operating Process","Online Output Program","Ordered Operation Procedure"], answer: 0 },
{ q: "What is the binary representation of the decimal number 5?", options: ["100","101","110","111"], answer: 1 },
{ q: "What is a 'compiler'?", options: ["A program that translates source code into machine code","A type of variable","A network device","A database manager"], answer: 0 },
{ q: "Which of these is an example of cloud storage?", options: ["Google Drive","USB Flash Drive","CD-ROM","Hard Disk"], answer: 0 },
{ q: "What is 'encryption' used for?", options: ["Speeding up data transfer","Securing data by converting it into code","Compressing files","Deleting data"], answer: 1 },
{ q: "What does 'CSS' stand for in web development?", options: ["Computer Style Sheets","Cascading Style Sheets","Creative Style Software","Coded Style System"], answer: 1 }
],
"General Knowledge": [
{ q: "What is the capital of Ghana?", options: ["Kumasi","Accra","Tamale","Cape Coast"], answer: 1 },
{ q: "Which planet is known as the Red Planet?", options: ["Earth","Mars","Jupiter","Venus"], answer: 1 },
{ q: "What is the largest continent by area?", options: ["Africa","Asia","Europe","Antarctica"], answer: 1 },
{ q: "How many continents are there?", options: ["5","6","7","8"], answer: 2 },
{ q: "Which is the longest river in the world?", options: ["Nile","Amazon","Yangtze","Mississippi"], answer: 0 },
{ q: "Who proposed the theory of relativity?", options: ["Isaac Newton","Albert Einstein","Stephen Hawking","Niels Bohr"], answer: 1 },
{ q: "What is the smallest unit of life?", options: ["Atom","Cell","Tissue","Organ"], answer: 1 },
{ q: "Which gas makes up the majority of Earth's atmosphere?", options: ["Oxygen","Carbon dioxide","Nitrogen","Hydrogen"], answer: 2 },
{ q: "What year did Ghana gain independence?", options: ["1957","1960","1963","1966"], answer: 0 },
{ q: "What is the currency of Ghana?", options: ["Naira","Cedi","Franc","Dollar"], answer: 1 },
{ q: "Which country has the largest population in the world (as commonly cited)?", options: ["USA","China","India","Indonesia"], answer: 2 },
{ q: "What is the smallest country in the world by land area?", options: ["Monaco","Vatican City","San Marino","Liechtenstein"], answer: 1 },
{ q: "What is the tallest mountain in the world?", options: ["K2","Mount Everest","Kilimanjaro","Denali"], answer: 1 },
{ q: "Who wrote the play 'Romeo and Juliet'?", options: ["Charles Dickens","William Shakespeare","Mark Twain","Jane Austen"], answer: 1 },
{ q: "What is the largest ocean on Earth?", options: ["Atlantic","Indian","Arctic","Pacific"], answer: 3 },
{ q: "Which African country was formerly known as the Gold Coast?", options: ["Nigeria","Ghana","Senegal","Kenya"], answer: 1 },
{ q: "What is the official language of Brazil?", options: ["Spanish","Portuguese","French","English"], answer: 1 },
{ q: "Which organ in the human body produces insulin?", options: ["Liver","Pancreas","Kidney","Stomach"], answer: 1 },
{ q: "What is the currency of Japan?", options: ["Won","Yuan","Yen","Ringgit"], answer: 2 },
{ q: "Who was the first President of the United States?", options: ["Thomas Jefferson","Abraham Lincoln","George Washington","John Adams"], answer: 2 },
{ q: "What is the largest desert in the world?", options: ["Sahara","Gobi","Antarctic Desert","Kalahari"], answer: 2 },
{ q: "Which gas do plants absorb that humans exhale?", options: ["Oxygen","Carbon dioxide","Nitrogen","Hydrogen"], answer: 1 },
{ q: "What is the speed of light approximately (in km/s)?", options: ["150,000","300,000","450,000","600,000"], answer: 1 },
{ q: "Which country is known as the Land of the Rising Sun?", options: ["China","South Korea","Japan","Thailand"], answer: 2 },
{ q: "What does 'WHO' stand for?", options: ["World Health Organization","World Humanitarian Office","World Health Office","World Human Organization"], answer: 0 }
],
"Biology": [
{ q: "What is the basic unit of heredity?", options: ["Cell","Gene","Atom","Tissue"], answer: 1 },
{ q: "What process do cells use to divide and produce identical copies?", options: ["Meiosis","Mitosis","Osmosis","Diffusion"], answer: 1 },
{ q: "Which molecule primarily carries genetic information?", options: ["RNA","DNA","ATP","Protein"], answer: 1 },
{ q: "What is the function of mitochondria?", options: ["Protein synthesis","Energy production","Waste removal","Cell division"], answer: 1 },
{ q: "What is photosynthesis primarily used to produce?", options: ["Oxygen and glucose","Carbon dioxide and water","Nitrogen and protein","Salt and minerals"], answer: 0 },
{ q: "Which kingdom do bacteria belong to?", options: ["Animalia","Plantae","Fungi","Monera"], answer: 3 },
{ q: "What is the term for an organism's complete set of DNA?", options: ["Genome","Phenotype","Genotype","Chromosome"], answer: 0 },
{ q: "Which blood type is considered the universal donor?", options: ["A","B","AB","O negative"], answer: 3 },
{ q: "What is homeostasis?", options: ["Cell division","Maintaining a stable internal environment","Reproduction","Mutation"], answer: 1 },
{ q: "Which structure controls what enters and leaves a cell?", options: ["Nucleus","Cell membrane","Cytoplasm","Ribosome"], answer: 1 },
{ q: "What is the function of red blood cells?", options: ["Fight infection","Carry oxygen","Clot blood","Produce hormones"], answer: 1 },
{ q: "What is the term for an organism's response to a stimulus?", options: ["Metabolism","Homeostasis","Reflex","Adaptation"], answer: 2 },
{ q: "Which kingdom do mushrooms belong to?", options: ["Plantae","Animalia","Fungi","Protista"], answer: 2 },
{ q: "What is the powerhouse organelle responsible for ATP production?", options: ["Nucleus","Mitochondria","Ribosome","Vacuole"], answer: 1 },
{ q: "What is the process by which water moves across a cell membrane?", options: ["Diffusion","Osmosis","Active transport","Filtration"], answer: 1 },
{ q: "What are the building blocks of proteins called?", options: ["Nucleotides","Amino acids","Fatty acids","Monosaccharides"], answer: 1 },
{ q: "What is the term for a population's ability to survive environmental change?", options: ["Mutation","Adaptation","Extinction","Migration"], answer: 1 },
{ q: "Which structure in plant cells is responsible for photosynthesis?", options: ["Mitochondria","Chloroplast","Nucleus","Vacuole"], answer: 1 },
{ q: "What is the term for two different species living together where both benefit?", options: ["Parasitism","Commensalism","Mutualism","Predation"], answer: 2 },
{ q: "What is the main function of the respiratory system?", options: ["Digest food","Exchange gases","Pump blood","Filter waste"], answer: 1 },
{ q: "What is DNA's full name?", options: ["Deoxyribonucleic acid","Dinucleic acid","Diribonucleic acid","Deoxyribose acid"], answer: 0 },
{ q: "What is the term for the variety of life in an ecosystem?", options: ["Biomass","Biodiversity","Biosphere","Biocapacity"], answer: 1 },
{ q: "Which blood type can donate to all other blood types?", options: ["A","B","AB","O negative"], answer: 3 },
{ q: "What is the function of white blood cells in the body?", options: ["Carry oxygen","Fight infections","Clot wounds","Transport nutrients"], answer: 1 },
{ q: "What is the term for an organism that produces its own food?", options: ["Consumer","Decomposer","Producer","Predator"], answer: 2 }
]
}
}
};
